- name: "Command test"
  command:
    cmd: 'hostname'
  register: output

- name: "Debug msg"
  debug:
    msg: "{{ output }}"

- name: "docker-compose stop"
  command:
    cmd: 'docker-compose stop'
    chdir: "{{ src_dir }}"
  register: output

- name: "Debug msg"
  debug:
    msg: "{{ output }}"

- name: "docker-compose start"
  command:
    cmd: 'docker-compose start'
    chdir: "{{ src_dir }}"
  register: output

- name: "Debug msg"
  debug:
    msg: "{{ output }}"
