- name: "Command test"
  command:
    cmd: 'hostname'
  register: output

- name: "Debug msg"
  debug:
    msg: "{{ output }}"

- name: "Restart services"
  community.docker.docker_compose:
    project_src: "{{ src_dir }}"
    build: false
    restarted: true
  register: output

- name: "Debug msg"
  debug:
    msg: "{{ output }}"
